name: ipapi
description: Geolocation plugin for Flutter based on ip-api.com. Supports both free and pro access.
version: 1.0.1
repository: https://github.com/mk-dev-1/ipapi

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.2
  build_runner: ^2.2.1
